/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorIndication_ECU_Abstraction_SWC_Type.h
 * Generated on: Sun Aug 4 16:40:13 EET
 ********************************************************************/

#ifndef RTE_DOORINDICATION_ECU_ABSTRACTION_SWC_TYPE_H
#define RTE_DOORINDICATION_ECU_ABSTRACTION_SWC_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/

#define uint8_LowerLimit  (0U)
#define uint8_UpperLimit (255U)

/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_DOORINDICATION_ECU_ABSTRACTION_SWC_TYPE_H */
